### ISSUE TITLE
Combile debug fail in new app

### ISSUE THREAD

**Issue by outrowender** [Scandit/scandit-flutter-datacapture-core#1]
## CompileDebugKotlin error
Im trying to install sdk in Flutter but i get following compile error:

```bash
Execution failed for task ':scandit_flutter_datacapture_core:compileDebugKotlin'.

ScanditFlutterDataCaptureCoreMethodHandler.kt: (52, 38): Expecting a parameter declaration
SerializableAimerViewfinderDefaults.kt: (19, 74): Expecting an argument
```

## Steps to reproduce:

* Create new app with `fluter create barcodeapp `

* In main build.gradle update `minSdkVersion 17` to `minSdkVersion 19`

* add to `pubspec.yaml`:
```yaml
scandit_flutter_datacapture_core: 6.7.1
scandit_flutter_datacapture_barcode: 6.7.1
```

* Run `flutter pub get`

* Run `fluter run`

## Environment
```bash
Flutter Channel stable, 2.0.4, on Linux, locale en_US.UTF-8
Android toolchain - develop for Android devices (Android SDK version 30.0.3)
Connected device (3 available)

Scandit sdk: 6.7.1
```

**Comment by ScanditSupport** [comment]
@outrowender the issue might be related to a Kotlin version difference. Could you please check if the Kotlin version is set to 1.4.10 in APP_FOLDER/android/build.gradle?
In case the issue persists, please reach out to us vi the webform support.scandit.com and we can support you on your individual issue. 

We will also look into how we can improve the Kotlin version dependencies in future releases.

Best regards
Scandit Support

**Comment by outrowender** [comment]
This solved the issue. 

BTW, any plans to support Dart sound nulll safe in future releases?

Thanks for your help!

**Comment by ScanditSupport** [comment]
@outrowender great that you solved it. Dart Null safety is planned for the next release. If you reach out to us, we can inform you once it's released (support.scandit.com)
