### ISSUE TITLE
Unable to build a project with Flutter 3.0+

### ISSUE THREAD

**Issue by movaid7** [Scandit/scandit-flutter-datacapture-core#4]
I am currently dealing with the issue described here:
https://github.com/Scandit/datacapture-flutter-samples/issues/4#issue-1251891904

A fix for the core plugin was detailed in June [here](https://github.com/Scandit/datacapture-flutter-samples/issues/4#issuecomment-1154893311) but still doesn't look to have been implemented - as a result, the Flutter barcode scanner SDK does not work with Flutter 3.0+ projects at this point in time.

Is there any timeline for when the bug fix will be released?

**Comment by ScanditSupport** [comment]
Hi @movaid7 

Thank you for your message.

Please note that our new beta release of version 6.14.0-beta.1 supports Flutter 3.x. The stable version should be available within 1-2 weeks depending on the QA process. 

In case you have more detailed questions, please feel free to reach out to us directly:
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
